INSERT INTO leki (nazwa_leku, producent, cena, typ, substancja_czynna, dawka) 
VALUES ("Paracetamol", "Pfizer", 12.50, "tabletka", "paracetamol", "500mg"),
("Ibuprofen", "Novartis", 19.99, "kapsułka", "ibuprofen", "200mg"),
("Omeprazol", "AstraZeneca", 29.95, "kapsułka", "omeprazol", "20mg"),
("Aspiryna", "Bayer", 8.75, "tabletka", "kwas acetylosalicylowy", "100mg"),
("Amoksycylina", "GlaxoSmithKline", 15.20, "tabletki", "amoksycylina", "500mg"),
("Atorwastatyna", "Merck", 32.40, "tabletka", "atorwastatyna", "10mg"),
("Losartan", "Sanofi", 27.85, "tabletka", "losartan", "50mg"),
("Metformina", "Roche", 18.60, "tabletka", "metformina", "850mg"),
("Ciprofloksacyna", "Bristol-Myers Squibb", 22.75, "tabletki", "ciprofloksacyna", "500mg"),
("Deksametazon", "Johnson & Johnson", 45.30, "tabletki", "deksametazon", "4mg"),
("Izotretynoina", "AbbVie", 38.90, "kapsułka", "izotretynoina", "20mg"),
("Ketoprofen", "Eli Lilly", 17.60, "tabletki", "ketoprofen", "100mg"),
("Lewocetyryzyna", "Pfizer", 28.75, "tabletka", "lewocetyryzyna", "5mg"),
("Montelukast", "Novartis", 23.20, "tabletka", "montelukast", "10mg"),
("Naproxen", "AstraZeneca", 14.90, "kapsułka", "naproksen", "220mg"),
("Oksykodon", "Bayer", 50.25, "tabletki", "oksykodon", "10mg"),
("Pantoprazol", "GlaxoSmithKline", 19.99, "tabletka", "pantoprazol", "40mg"),
("Ranitidyna", "Merck", 12.35, "tabletka", "ranitidyna", "150mg"),
("Sertralina", "Sanofi", 30.80, "kapsułka", "sertralina", "50mg"),
("Telmisartan", "Roche", 25.15, "tabletka", "telmisartan", "40mg"),
("Warfarina", "Bristol-Myers Squibb", 18.70, "tabletki", "warfaryna", "2.5mg"),
("Zolpidem", "Johnson & Johnson", 22.40, "tabletki", "zolpidem", "10mg"),
("Acetylocysteina", "AbbVie", 14.90, "tabletka", "acetylocysteina", "200mg"),
("Budesonid", "Eli Lilly", 31.50, "kapsułka", "budesonid", "3mg"),
("Cefuroksym", "Pfizer", 26.80, "tabletki", "cefuroksym", "500mg"),
("Difenylohydantoina", "Novartis", 35.25, "tabletka", "difenylohydantoina", "100mg"),
("Ezetimib", "AstraZeneca", 42.90, "tabletka", "ezetimib", "10mg"),
("Fenylobutazon", "GlaxoSmithKline", 18.40, "tabletki", "fenylobutazon", "100mg"),
("Gliclazid", "Merck", 20.75, "tabletka", "gliclazid", "80mg"),
("Hydroksyzyna", "Sanofi", 14.60, "kapsułka", "hydroksyzyna", "25mg"),
("Izoniazyd", "Roche", 27.90, "tabletki", "izoniazyd", "300mg"),
("Kwas foliowy", "Bristol-Myers Squibb", 9.99, "tabletka", "kwas foliowy", "400mcg"),
("Lizynopryl", "Johnson & Johnson", 21.30, "kapsułka", "lizynopryl", "10mg"),
("Metoklopramid", "AbbVie", 16.75, "tabletka", "metoklopramid", "10mg"),
("Nystatyna", "Eli Lilly", 25.40, "kapsułka", "nystatyna", "100000IU"),
("Olanzapina", "Pfizer", 38.20, "tabletki", "olanzapina", "5mg"),
("Piracetam", "Novartis", 12.90, "tabletka", "piracetam", "800mg"),
("Ropinirol", "AstraZeneca", 29.60, "tabletka", "ropinirol", "1mg"),
("Salmeterol", "GlaxoSmithKline", 34.15, "kapsułka", "salmeterol", "25mcg"),
("Tenofovir", "Merck", 40.90, "tabletki", "tenofovir", "300mg"),
("Valacyklowir", "Sanofi", 22.75, "tabletka", "walacyklowir", "500mg"),
("Witamina B12", "Roche", 16.20, "tabletka", "witamina B12", "1000mcg"),
("Xylometazolin", "Bristol-Myers Squibb", 8.50, "kapsułka", "ksylometazolina", "1mg"),
("Yohimbina", "Johnson & Johnson", 45.80, "tabletki", "johimbina", "5mg"),
("Zinc", "AbbVie", 10.25, "tabletka", "cynk", "25mg"),
("Amlodypina", "Eli Lilly", 19.70, "tabletka", "amlodypina", "5mg");