INSERT INTO specjalizacje VALUES 
(6, "Dermatolog dzieciency"),
(7, "Ginekolog"),
(8, "Ortopeda"),
(9, "Pediatra"),
(10, "Okulista dzieciency"),
(11, "Chirurg"),
(12, "Internista"),
(13, "Neurolog"),
(14, "Psychiatra"),
(15, "Onkolog"),
(16, "Reumatolog"),
(17, "Urolog meski"),
(18, "Endokrynolog"),
(19, "Pulmonolog"),
(20, "Nefrolog"),
(21, "Ortodonta"),
(22, "Chirurg plastyczny"),
(23, "Stomatolog"),
(24, "Fizjoterapeuta"),
(25, "Laryngolog dzieciency"),
(26, "Radiolog"),
(27, "Hematolog"),
(28, "Immunolog"),
(29, "Alergolog"),
(30, "Genetyk"),
(31, "Epidemiolog"),
(32, "Chirurg naczyniowy"),
(33, "Onkolog kliniczny"),
(34, "Radioterapeuta"),
(35, "Geriatria"),
(36, "Proktolog"),
(37, "Diabetolog"),
(38, "Audiolog"),
(40, "Alergolog dziecięcy"),
(41, "Pediatra metaboliczny"),
(42, "Neurochirurg"),
(43, "Psychoterapeuta"),
(44, "Balneolog"),
(45, "Onkolog radioterapeuta"),
(46, "Neurolog dziecięcy"),
(47, "Psychiatra dziecięcy"),
(48, "Rehabilitant"),
(49, "Ortoptyk"),
(50, "Flebolog"),
(51, "Chirurg maxillofacialny"),
(52, "Chirurg klatki piersiowej"),
(53, "Chirurg plastyczny dziecięcy"),
(54, "Alergolog i immunolog dziecięcy"),
(55, "Endokrynolog dziecięcy"),
(56, "Gastroenterolog dziecięcy"),
(57, "Kardiolog dziecięcy"),
(58, "Reumatolog dziecięcy"),
(59, "Neonatolog"),
(60, "Onkolog dziecięcy"),
(61, "Geriatria kliniczna"),
(62, "Epidemiolog dziecięcy"),
(63, "Pediatria rodzinna"),
(64, "Lekarz ogólny");